---
- name: Set Up AWS Instance 
  hosts: aws-instance 
  tasks:
      - hostname: name=docker
      - apt: "upgrade=dist state=present update_cache=true cache_valid_time=600"
      - apt: "name={{ item }} state=present"
        with_items:
           - python-setuptools
      - command: easy_install pip

